// Multi Middleware
export const MULTI = "MULTI";

// Api middleware
export const API_START = "API_START";
export const API_END = "API_END";

// City constants
export const ADD_CITY = "ADD_CITY";
export const FETCH_CURRENT_WEATHER = "FETCH_CURRENT_WEATHER";
export const FETCH_CURRENT_WEATHER_PENDING = "FETCH_CURRENT_WEATHER_PENDING";
export const FETCH_CURRENT_WEATHER_SUCCESS = "FETCH_CURRENT_WEATHER_SUCCESS";
export const FETCH_CURRENT_WEATHER_ERROR = "FETCH_CURRENT_WEATHER_ERROR";
export const SET_CURRENT_WEATHER = "SET_CURRENT_WEATHER";
